language: generic
env:
  - KUBECTL_VERSION=1.9.2 BUILD=1 DISTRO=debian
  - KUBECTL_VERSION=1.9.2 BUILD=1 DISTRO=debian
  - KUBECTL_VERSION=1.10.2 BUILD=1 DISTRO=alpine
  - KUBECTL_VERSION=1.10.2 BUILD=1 DISTRO=alpine

services:
  - docker

install:
  - ./build-image.sh

script:
  - ./test.sh
