FROM alpine:3.7

ARG ver
ENV VERSION=$ver

RUN apk add --no-cache bash curl gettext

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v$VERSION/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh
